### ISSUE TITLE
nuke start errors

### ISSUE THREAD

**Issue by lucky0511** [Theo-SAMINADIN-td/NukeDepthCrafter#3]
Hello, I have an issue please, I need some help to make it work.

1,2. downloaded file/model with the same trees as yours

3. Confirm Python 3.10.10 , env set
    Dependencies installed to default Python location 

4. init.py added my env python 
nuke.pluginAddPath("C:/Users/VFX-Admin/AppData/Local/Programs/Python/Python310/Lib/site-packages")

***nuke 15.1 reported

> "Key already registered with the same priority: C10"

****nuke 15.0 reported

> Traceback (most recent call last):
>   File "C:/Users/VFX-Admin/.nuke/NukeDepthCrafter/menu.py", line 1, in <module>
>     from nukedc import UpdateBtn, CreateDCNode, GenerateDepthAction
>   File "C:\Program Files\Nuke15.0v4\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "C:\Users/VFX-Admin/.nuke/NukeDepthCrafter\nukedc.py", line 2, in <module>
>     from DepthCrafterPlugin.utils import *
>   File "C:\Program Files\Nuke15.0v4\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "C:\Users/VFX-Admin/.nuke/NukeDepthCrafter\DepthCrafterPlugin\utils.py", line 6, in <module>
>     import torch
>   File "C:\Program Files\Nuke15.0v4\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "C:\Users\VFX-Admin\AppData\Local\Programs\Python\Python310\Lib\site-packages\torch\__init__.py", line 128, in <module>
>     raise err
> OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\VFX-Admin\AppData\Local\Programs\Python\Python310\Lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

pendencies.

**Comment by IIWstudio** [comment]
I have the same issue, i tried many things like installing other version of torch. With the latest version the error changes but didn't find a way to make it work. 
I'll keep an eye here if you find a solution :)

**Comment by AlbertoF-LP** [comment]
I have the same issue on Nuke 15.1 too. 

What I see is seems to be a problem due to Nuke comes with a pre-installed version of PyTorch (as is shown in the third-party libraries on the docs) so when installing another version, the error you said above raises... The thing is I am not able to import the pre-installed PyTorch within Nuke and I haven't found the files in the installation directory... I'm a little bit lost here :(

Have you found any solution?

**Comment by Theo-SAMINADIN-td** [comment]
Hi, I have not been able to reproduce your exact error, but it might be still worth trying.
 
Only by installing Pytorch 2.3.0 or 2.3.1 :

Nuke is returning me this error : 

>  File "C:\Users/Theo/AppData/Local/Programs/Python/Python310/Lib/site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users/Theo/AppData/Local/Programs/Python/Python310/Lib/site-packages\torch\lib\shm.dll" or one of its dependencies.

Going back to previous Pytorch versions did the work. 

Sadly, I don't have more informations about this specific issue :/
If you manage to solve this tell me !

**Comment by LukemanX** [comment]
Has anyone had any news regarding this?

I am still getting the same errors described here after months of trying on and off.

Thanks!

**Comment by lucky0511** [comment]
well I tried many way, up and down some package version does not work .
So I decided to try the Tencent way, just use cmd to run that stuff.

**Comment by AlbertoF-LP** [comment]
Hi!

I've tried several things but finally, for me, installing the required version of Pytorch without installing torchvision is the one that make it work. :)

**Comment by LukemanX** [comment]
Thanks a lot both of your replies. I will try again with these suggestions in mind and confirm if it fixed the issue for me.

**Comment by LukemanX** [comment]
> Hi!
> 
> I've tried several things but finally, for me, installing the required version of Pytorch without installing torchvision is the one that make it work. :)

Hi!

By the required version of pytorch you mean "torch 2.0.1+cu118", right?

That's the one that gets installed following the install procedure and as far as I can tell it doesn't install torchvision when following those instructions.

If you don't mind me asking, what version of Nuke are you running? Is it a python virtual environment or not? Are you on python 3.10.10 as instructed? And also, where are your site-packages located in a general sense?

Did you at any point get something similar to this?
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\python_venv\nukeDepthCrafter\Lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

Thanks!

**Comment by AlbertoF-LP** [comment]
Hi again!

In my side, I am using Nuke 15.1v2. I have a shared volume with all the Nuke config (NUKE_PATH),  I've created there a folder with all the python packages installed in my python 3.10 and added this location to my PYTHONPATH.

The version of pytorch yes I mean that one. I did so many tests and I do not remember which one was the right one hahaha but finally, for me, works with that.

You should look also your Cattery plugins, when I was trying it there was some of them I had to disable before having DepthCrafter running. I think there was kind of a version missmatch between some libraries already installed for those plugins. I recomend you to disable all and try again, then you can go further and get the one making the missmatch.
