### ISSUE TITLE
Tencent license

### ISSUE THREAD

**Issue by anders-d** [Theo-SAMINADIN-td/NukeDepthCrafter#4]
Hi,

Do you know how an integration like this would comply to the Tencent license Depthcrafter is released under?

https://github.com/Tencent/DepthCrafter/blob/main/LICENSE

" You agree to use the DepthCrafter only for academic, research and education purposes, and refrain from using it for any commercial or production purposes under any circumstances."

**Comment by Theo-SAMINADIN-td** [comment]
HI @anders-d, 
As you say, for the moment this tool can only be used for ‘academic, research and educational purposes’. As long as the project stays within this framework, it's fine.

**Comment by Theo-SAMINADIN-td** [comment]
HI @anders-d,
As you say, for the moment this tool can only be used for ‘academic, research and educational purposes’. As long as the project stays within this framework, it's fine.
