### ISSUE TITLE
Benchmarking DepthCrafter vs ML depth pro

### ISSUE THREAD

**Issue by hbardak** [Theo-SAMINADIN-td/NukeDepthCrafter#8]
Hi everyone,

Thank for porting this to nuke. 

I did a quick comparison DepthCrafter and ml depth pro from Apple.

https://github.com/user-attachments/assets/0d152c1a-881f-4d0e-87c7-419cf61c3b11

Here the take away : 

- DepthCrafter consistency is amazing if you have enough VRAM
- Need to run the whole sequence at once otherwise you have a reset of the depth data 
- Limited resolution because of the VRAM of your GPU
- DepthCrafter isn't metric so the depth data is skewed and non representative real depth data

**Comment by Theo-SAMINADIN-td** [comment]
Hi @hbardak, this is very interesting! Thanks for sharing 🙏
